FROM rockylinux/rockylinux:latest
CMD sudo dnf -y install java-11-openjdk curl zip
CMD curl -OL https://github.com/keycloak/keycloak/releases/download/18.0.2/keycloak-18.0.2.zip
CMD unzip keycloak-18.0.2.zip




