services:
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.0
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    entrypoint:
      - /opt/keycloak/bin/kc.sh
      - start-dev

  reverse_proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.3.0
    container_name: oauth2proxy

  reverse_proxy_by_apache:
    image: httpd:2.4
    container_name: apache_as_reverse_proxy
    ports:
      - "80:80"

  db:
    image: postgres:14.4
    container_name: postgresql_for_api
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--no-locale"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./pginit:/docker-entrypoint-initdb.d
